### ISSUE TITLE
Template Export uses Hard Coded Coordinates for Export

### ISSUE THREAD

**Issue by yashTEF** [eclipse/swtchart#174]
The template export works fine but uses hard coded coordinates for setting positions of legends
etc,
e.g- start=80.804.
Instead we need to set the above using some relative positions depending on the borders of the template

**Comment by yashTEF** [comment]
A possible way forward to solve this could be to change values of the hard coded coordinates using
the XML (SVG) Document Object Model and set the coordinates accordingly.

**Comment by eselmeister** [comment]
Yep, that could be a solution. In such a case, at least the following dependency is needed:
`org.w3c.dom.events`

The export via an SVG template is designed in a very simple way, so that no external dependencies are required. The contained templates in `org.eclipse.swtchart.export` could be extended by a Pie-, Doughnut-Chart version.

Due to the Batik dependencies, the enhanced SVG export has been moved to the bundle:
`org.eclipse.swtchart.export.extended`

It keeps the overhead of SWTChart small. If one would like to use the extended export, its up to the user to decide whether it's reasonable to include additional dependencies or if the overhead is too high.

**Comment by eselmeister** [comment]
The vectorgraphics2d library for dynamic export of SVG files has been added. Hence, the template system will be replaced soon.
