### ISSUE TITLE
Replacement for Series#setXDateSeries?

### ISSUE THREAD

**Issue by buchen** [eclipse/swtchart#53]
For my [project](https://github.com/buchen/portfolio), I used to rely on ```ISeries#setXDateSeries(Date[] series)```. This method seems to be gone. What do you propose to do? Most of my compile errors are due to the get/setXDateSeries change and I am wondering how to best refactor my code.

I know I could convert myself to double via ```Date#toTime```. Is that the proposed solution?

Do you plan to provide a model implementing ```CartesianSeriesModel``` also for Date (or even LocalDate)? And then provide the setXDateSeries methods for backwards compatibility. I believe it could be beneficial also for other adopters to keep the changes to the API changes fairly small.

What are your plans on API compatibility? I know SWTChart never was a 1.x release and by moving to Eclipse and naming it 0.7.0, there is no necessity on API compatibility. I am trying to understand if and how I can help.

BTW, I see the documentation still contains the reference to setXDateSeries: http://swtchart.org/doc/index.html#Axis_Tick_Format

**Comment by laeubi** [comment]
Hi @buchen you are right, best would be (for now) to provide the longs itself. the problem with the Date[] was that it was a support for a very special usecase (displaying dates on axis) but cluttered the code with several cases to take care of (e.g. converting back and forth the long values to dates, check in axis formating if it is a date axis and so on).
As there are other use cases (think about Weekdays, or any non nummeric axis labels) we want to provide a more general aproach for these cases.
Sadly the labeling is not yet finished but I'm working on this, so you einter has to use the "old 0.7" version or wait until this is fixed.
If you tell me what methods in particular you miss (only setXDateSeries?) I can check if i can provide backward compatible method signatures

**Comment by laeubi** [comment]
If you like, test out the branch I just created ad let me know whats missing.

**Comment by buchen** [comment]
If have tested the branch. Thanks.

This is what I had to change to make it kind of work:
* Re-added a ```getXDateSeries``` method in ```ISeries```
* Cast ```Chart#getPlotArea```  to ```Composite``` wherever used:
  * added PaintListener -> is not a functional interface anymore (maybe one can add a default implementation of the method ```#drawBehindSeries``` to allow lambdas in at least on case)
  * I am using the Composite directly to handle custom tool tips of data, my own context menus, add key, mouse, and key traversal listener, ...

I have to check further because some of my custom paint listener do not yet work as expected and the tooltips as well (I assume my getXDateSeries is not correctly implemented).

```java
	@Override
	public Date[] getXDateSeries() {

		CartesianSeriesModel<T> dataModel = getDataModel();
		if(dataModel == null) {
			return new Date[0];
		}
		return StreamSupport.stream(dataModel.spliterator(), false).filter(t -> dataModel.getX(t) != null).map(value -> new Date(dataModel.getX(value).longValue())).toArray(Date[]::new);
	}
```

I am happy to change code though.


* Is the idea to use #setDataModel instead of #setXDateSeries?

* And: the ISeries#setDataModel takes a CartesianSeriesModel as input - shouldn't it be the IDataModel instead? Or asked the other way around: I see no usage of the IDataModel<T> interface.

* Is it okay to cast getPlotArea to Composite? Or is there a better way to get to the Composite?

**Comment by buchen** [comment]
> I have to check further because some of my custom paint listener do not yet work as expected and the tooltips as well 

The reason seems to be that this code behaves different now: The result is not the time anymore.
```
long time = (long) xAxis.getDataCoordinate(event.x);
```

**Comment by buchen** [comment]
> Sadly the labeling is not yet finished but I'm working on this, so you einter has to use the "old 0.7" version or wait until this is fixed.

BTW, axis labeling is not a problem for me. I am not labelling the x axis (only the y axis).

**Comment by laeubi** [comment]
Thanks for the feedback I applied the following changes:

- ICustomPaintListener is now a functional interface
- getXDateSeries is added back
- Add getControl() method to IPlotarea for extended usecases
- Fix DateArraySeriesModel so the x value is the date/time

**Comment by laeubi** [comment]
> Is the idea to use #setDataModel instead of #setXDateSeries?

Yes, this has several advantages, for example I assume that your ObjectModel is not based on Date[] and double[] but some kind of Business Case, you can now implement a mapping for the char very intuitive.

Assume we have this simple OM:
```
public interface BusinessObject {

	double getPrice();

	Date getTimeOfBuying();
}
```
And you want to plot `Price` over `TimeOfBuying` you can implement it the following way:
```
public class BusinessObjectModel implements CartesianSeriesModel<BusinessObject> {

	private Supplier<Iterator<BusinessObject>> supplier;

	public BusinessObjectModel(Supplier<Iterator<BusinessObject>> supplier) {
		this.supplier = supplier;
	}

	@Override
	public Iterator<BusinessObject> iterator() {

		return supplier.get();
	}

	@Override
	public Number getX(BusinessObject data) {

		return data.getTimeOfBuying().getTime();
	}

	@Override
	public Number getY(BusinessObject data) {

		return data.getPrice();
	}
}
```
This is much easier to understand and debug (e.g. if you don't have to count indices anymore) and as mentioned before I wan't to extend this so for example you can provide custom label for x-axis items and so on.
The second thing is, that Supplier<BusinessObject> can be anything, from a static collection to a query to the database, so a simple chart.redraw() can update from your underlying data-source, no need to recreate series data/arrays.

> Or asked the other way around: I see no usage of the IDataModel interface

The SeriesModel only contains the basic data acquisition function, CartesianSeriesModel adds methods to obtain coordinates from the model, currently the Series are limited to plotting X/Y data thats why it requires a CartesianModel. Other parts of the code (e.g. Labelprovider) might work on a SeriesModel extension that provides Labels instead of coordinates.

> Is it okay to cast getPlotArea to Composite? Or is there a better way to get to the Composite?

I added a getControl() method as it seems there is a high demand on accessing the control it self, the idea is simply that we allow different plotting area implementations, for example I'm working on an implementation that uses [JOGL](https://jogamp.org/jogl/www/) as the backing rendering engine.

Anyways if you like you can always open an enhancement request and describe your use-case, so you can archive your goal without custom implementation but standard SWTChart functions.

**Comment by laeubi** [comment]
Changes where merged to develop branch, please check if anything is missing and then close the issue.

**Comment by buchen** [comment]
Thanks @laeubi.

My code using get/setXDateSeries in now working. I noticed a small problem when comparing the lengths of the both data series - see PR #63

I see that I find time to rework my usage of SWTChart to use IDataModel. Indeed I am actually working with LocalDate internally and always have to convert it to java.util.Date for SWTChart.

**Comment by laeubi** [comment]
Yes thats why I have deprecated this in favor of Datamodel, you have the same problem with Calendar or JodaTime or ...

By the way, there is even no need to return the time() value as X, if you data is for example organized as list, you can simply retun the index of the Localdate as X-Value, you then just have to adjust your  `long time = (long) xAxis.getDataCoordinate(event.x);` to int index= (int) xAxis.getDataCoordinate(event.x); and can then simply get your item with list.get(index)
